server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pixivimages
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
mybatis:
  type-aliases-package: com.myproject.multifunctioncrawler.pojo
  configuration:
    map-underscore-to-camel-case: true
